# Generated by Django 2.2.26 on 2022-03-12 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectureFinderApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.IntegerField(default=0, max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.TextField(max_length=128),
        ),
    ]
