# Generated by Django 2.2.26 on 2022-03-12 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectureFinderApp', '0002_auto_20220312_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
