# Generated by Django 2.2.26 on 2022-03-13 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectureFinderApp', '0003_auto_20220312_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='transcript_name',
            field=models.TextField(default='', max_length=128),
        ),
    ]
