# Generated by Django 2.2.26 on 2022-03-16 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectureFinderApp', '0004_lecture_transcript_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='slug',
            field=models.SlugField(default=None, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lecture',
            name='title',
            field=models.TextField(max_length=128, unique=True),
        ),
    ]
