# Generated by Django 2.2.26 on 2022-03-16 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectureFinderApp', '0005_auto_20220316_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='slideshow_url',
            field=models.URLField(max_length=400),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='video_url',
            field=models.URLField(max_length=400),
        ),
    ]
