# Generated by Django 2.2.26 on 2022-03-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectureFinderApp', '0006_auto_20220316_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='slug',
            field=models.SlugField(default=None, unique=True),
        ),
    ]
