# Generated by Django 2.2.26 on 2022-03-21 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectureFinderApp', '0007_auto_20220317_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='week',
            field=models.IntegerField(default=1),
        ),
    ]
