# Generated by Django 2.2.26 on 2022-03-25 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lectureFinderApp', '0008_lecture_week'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikedLecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lectureFinderApp.Lecture')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lectureFinderApp.UserProfile')),
            ],
        ),
    ]
